# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

COMBO_ENABLE = yes
# VIA_ENABLE = yes

RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
