#pragma once

#define TAPPING_TERM 250
#define QUICK_TAP_TERM 0
#define CHORDAL_HOLD

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY         0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL      16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY   0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED     6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX   64

#define DYNAMIC_KEYMAP_LAYER_COUNT 11
#define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE
